### ijk into matrix  and * d[1,1,1,1,1,1...]

In [30]:
import numpy
maxn=10
M=numpy.zeros((maxn,maxn))
with open('/Users/hanxinlei/tmp/adj_ijk.txt','r') as f:
    for line in f:
        if None==line: 
            continue
        x=int(line.strip().split()[0])
        y=int(line.strip().split()[1])        
        n=int(line.strip().split()[2])
        M[x][y]=n
d=numpy.ones((maxn,))
d=numpy.dot(d,M)
print(d)

[ 0.  4.  3.  3.  3.  1.  0.  0.  0.  0.]


### matrices into ijk

In [25]:
with open('/Users/hanxinlei/tmp/adj.txt','r') as f:
    with open('/Users/hanxinlei/tmp/adj_ijk.txt','w') as f1:
        i=0
        for row in f:
            x=row.strip().split()
            j=0
            for col in x:
                if(x[j]=='1'):
                    f1.write(str(i)+' '+str(j)+' '+x[j]+'\n')
                j+=1
            i+=1


### rj

In [34]:
import numpy
maxn=10
M=numpy.zeros((maxn,maxn))
with open('/Users/hanxinlei/tmp/adj_ijk.txt','r') as f:
    for line in f:
        if None==line: 
            continue
        x=int(line.strip().split()[0])
        y=int(line.strip().split()[1])        
        n=int(line.strip().split()[2])
        M[x][y]=n
d=numpy.ones((maxn,))
d=numpy.dot(d,M)
for i in d:
    if(i!=0):
        print('!!!!')
    
print(d)

!!!!
!!!!
!!!!
!!!!
!!!!
[ 0.  4.  3.  3.  3.  1.  0.  0.  0.  0.]


### 由一维或二维数据创建矩阵

In [35]:
from numpy import *;
a1=array([1,2,3]);
a1=mat(a1);

### matrix M

In [40]:
import numpy
maxn=10
M=numpy.zeros((maxn,maxn))
with open('/Users/hanxinlei/tmp/adj_ijk.txt','r') as f:
    for line in f:
        if None==line: 
            continue
        x=int(line.strip().split()[0])
        y=int(line.strip().split()[1])        
        n=int(line.strip().split()[2])
        M[x][y]=n
d=numpy.ones((maxn,))
d=numpy.dot(d,M)

i=0
for row in M:
    j=0
    for col in M[i]:
        if(M[i][j]!=0):
            M[i][j]/=d[j]
        j+=1
    i+=1
    
print(M)

[[ 0.          0.25        0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.33333333  0.33333333  0.33333333  0.          0.
   0.          0.          0.        ]
 [ 0.          0.25        0.          0.33333333  0.33333333  0.          0.
   0.          0.          0.        ]
 [ 0.          0.25        0.33333333  0.          0.33333333  0.          0.
   0.          0.          0.        ]
 [ 0.          0.25        0.33333333  0.33333333  0.          1.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0

In [67]:
import numpy
def check_stability(a,b):
    c=a-b
    for v in c:
        if v>0.1:
            return False
    
    return True

def pagerank(r,M):
    result_last=numpy.dot(M,r)
    beta=0.85
    for i in range(maxn):
        r=beta*numpy.dot(M,r)+(1-beta)*1/maxn
        check_stability(r,result_last)
        result_last=r
    return r

maxn=10
M=numpy.zeros((maxn,maxn))
with open('/Users/hanxinlei/tmp/adj_ijk.txt','r') as f:
    for line in f:
        if None==line: 
            continue
        x=int(line.strip().split()[0])
        y=int(line.strip().split()[1])        
        n=int(line.strip().split()[2])
        M[x][y]=n
d=numpy.ones((maxn,))
d=numpy.dot(d,M)

i=0
for row in M:
    j=0
    for col in M[i]:
        if(M[i][j]!=0):
            M[i][j]=M[i][j]/d[j]
        j+=1
    i+=1
    
r=numpy.ones((maxn,1))


pagerank(r,M)



array([[ 0.06766841],
       [ 0.21545123],
       [ 0.20224417],
       [ 0.20224417],
       [ 0.21216935],
       [ 0.015     ],
       [ 0.015     ],
       [ 0.015     ],
       [ 0.015     ],
       [ 0.015     ]])

In [10]:
import numpy
a=numpy.ones((10,))
a=a/10
print(a)

[ 0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1]


In [26]:
import numpy
a=numpy.array([[1,2,3],[4,5,6]])
b=numpy.array([1,2,3])
d=numpy.array([[1,2,3],[4,5,6]])
c=numpy.ones((1,3))
c=numpy.true_divide(a,c)
print(c)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [41]:
import numpy
#whether exit iteration
def check_stability(current,last,threshold):
    diff=current-last
    for val in diff:
        print(abs(val))
        if abs(val)>threshold:
            return False
    return True

#read M which is already initialized 
def pagerank(M,maxn,beta=0.85,threshold=0.001):
    r_last=r=numpy.ones((maxn,1))/maxn
    while True:
        r=beta*numpy.dot(M,r)+(1-beta)*1/maxn
        if(check_stability(r,r_last,threshold)):
            break
        r_last=r
    return r

#main()
#readfile
maxn=10
M=numpy.zeros((maxn,maxn))
with open('/Users/hanxinlei/tmp/adj_ijk.txt','r') as f:
    for line in f:
        if None==line: 
            continue
        x=int(line.strip().split()[0])
        y=int(line.strip().split()[1])        
        n=int(line.strip().split()[2])
        M[x][y]=n
d=numpy.ones((1,maxn))
d=numpy.dot(d,M)
#init M
for i in range(maxn):
    for j in range(maxn):
        if(d[0][j]>0):
            M[i][j]/=d[0][j]
#rank           
Rank=pagerank(M,maxn,threshold=0.0001)

[ 0.06375]
[ 0.]
[ 0.0180625]
[ 0.00383828]
[ 0.00217503]
[ 0.00053923]
[ 0.00069843]
[ 0.00049317]
[ 0.00040562]
[ 0.00031893]
[ 0.00025399]
[ 0.00020153]
[ 0.00016008]
[ 0.00012711]
[ 0.00010095]
[  8.01626732e-05]
[ 0.00029957]
[  6.36588633e-05]
[ 0.0002379]
[  5.05527387e-05]
[ 0.00018892]
[  4.01449341e-05]
[ 0.00015002]
[  3.18798844e-05]
[ 0.00011914]
[  2.53164466e-05]
[  9.46084259e-05]
[  8.83887261e-05]
[  8.83887261e-05]
[  8.83887394e-05]
[ 0.]
[ 0.]
[ 0.]
[ 0.]
[ 0.]
